description: 'Pull data from google sheet to generat visualized data chart'
name: 'Generate Chart from google sheet'
author: 'Ray Huang <general@rayhuang.dev>'
branding:
  icon: 'edit-3'
  color: 'blue'
inputs:
  IMG_DIR:
    description: 'the dir where the markdown will save in, Default: content/posts'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'